/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in a local account with email and password, and set the session cookie. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is signed in, and the organizations they may act in. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Where the identity provider sends the browser back; sets the session cookie. */
        get: operations["oIDCCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/{orgSlug}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin signing in through the organization's identity provider. */
        get: operations["oIDCStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/switch-org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move the session to another organization. */
        post: operations["switchOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the process is running. */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oidc-provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The organization's identity provider, if one is configured. For administrators. */
        get: operations["getOIDCProvider"];
        /** Configure the organization's identity provider. For administrators. */
        put: operations["saveOIDCProvider"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oidc-provider/group-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which provider groups grant which role. For administrators. */
        get: operations["listGroupRoles"];
        put?: never;
        /** Map a provider group to a role, or change the role it maps to; members follow at their next sign-in. For administrators. */
        post: operations["setGroupRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oidc-provider/group-roles/{groupRoleID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unmap a provider group; the roles it granted go at each person's next sign-in. For administrators. */
        delete: operations["removeGroupRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This document. */
        get: operations["openAPI"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the process can serve traffic, and how reads are routed. */
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Themes the caller may use: theirs, then the shared ones. */
        get: operations["listThemes"];
        put?: never;
        /** Make a theme. */
        post: operations["createTheme"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The theme the caller sees: chosen, the organization's default, or null for the built-in one. */
        get: operations["activeTheme"];
        /** Use a theme; null returns to the organization's default, null with builtIn keeps the built-in one. */
        put: operations["chooseTheme"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Name the shared theme everybody sees until they choose, or null for the built-in one. */
        put: operations["setDefaultTheme"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The themes shipped with the product, to start a theme from. */
        get: operations["themeExamples"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make a theme of the caller's own from an exported theme file, sent as a multipart part named file. */
        post: operations["importTheme"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes/{themeID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One theme. */
        get: operations["getTheme"];
        put?: never;
        post?: never;
        /** Delete a theme; everybody using it returns to the built-in one. */
        delete: operations["deleteTheme"];
        options?: never;
        head?: never;
        /** Change a theme; the owner's to do, or an administrator's once shared. */
        patch: operations["updateTheme"];
        trace?: never;
    };
    "/themes/{themeID}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Put a picture or a font on a theme, as a multipart part named file. */
        post: operations["uploadThemeAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes/{themeID}/assets/{assetID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The bytes of a theme's file, as a download. */
        get: operations["themeAsset"];
        put?: never;
        post?: never;
        /** Take a file off a theme it no longer uses. */
        delete: operations["deleteThemeAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes/{themeID}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The theme as one file, its pictures and fonts inside, as a download. */
        get: operations["exportTheme"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The organization's members, with their roles and whether the identity provider decides them. For administrators. */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who signed in through the identity provider and is waiting to be let in. For administrators. */
        get: operations["listJoinRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/requests/{userID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Turn a waiting person away; they may ask again. For administrators. */
        delete: operations["declineJoinRequest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/requests/{userID}/admit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Let a waiting person in with the standing given. For administrators. */
        post: operations["admitJoinRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Take somebody out of the organization. The owner stays. For administrators. */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIError: {
            code: string;
            fields?: {
                [key: string]: string;
            };
            message: string;
            requestId?: string;
        };
        AdmitRequest: {
            /** @enum {string} */
            role: "owner" | "admin" | "member";
        };
        Asset: {
            contentType: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            name: string;
            size: number;
        };
        Backdrop: {
            /** Format: uuid */
            assetId: string;
            /** @enum {string} */
            fit: "cover" | "tile";
        };
        ChooseThemeRequest: {
            builtIn?: boolean;
            /** Format: uuid */
            themeId: string | null;
        };
        Components: {
            schemas: {
                [key: string]: components["schemas"]["Schema"] | null;
            };
            securitySchemes?: {
                [key: string]: components["schemas"]["SecurityScheme"];
            };
        };
        CurrentOrg: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            role: "owner" | "admin" | "member";
            slug: string;
        };
        Cursor: {
            /** Format: uuid */
            assetId: string;
            hotspotX: number;
            hotspotY: number;
        };
        DefaultThemeRequest: {
            /** Format: uuid */
            themeId: string | null;
        };
        Document: {
            components: components["schemas"]["Components"];
            info: components["schemas"]["Info"];
            openapi: string;
            paths: {
                [key: string]: {
                    [key: string]: components["schemas"]["Operation"] | null;
                };
            };
            security?: {
                [key: string]: string[];
            }[];
            servers?: components["schemas"]["Server"][];
            tags?: components["schemas"]["Tag"][];
        };
        ErrorEnvelope: {
            error: components["schemas"]["APIError"];
        };
        Example: {
            description: string;
            key: string;
            name: string;
            spec: components["schemas"]["Spec"];
        };
        Font: {
            /** Format: uuid */
            assetId?: string;
            family: string;
        };
        Fonts: {
            mono?: components["schemas"]["Font"];
            sans?: components["schemas"]["Font"];
        };
        GroupRole: {
            group: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "admin" | "member";
            /** Format: date-time */
            updatedAt: string;
        };
        Icon: {
            /** Format: uuid */
            assetId?: string;
            paths?: string[];
        };
        Info: {
            description?: string;
            title: string;
            version: string;
        };
        Input: {
            name?: string;
            shared?: boolean;
            spec?: components["schemas"]["Spec"];
        };
        JoinRequest: {
            email: string;
            name: string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: uuid */
            userId: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MeResponse: {
            organization: components["schemas"]["CurrentOrg"] | null;
            organizations: components["schemas"]["Membership"][];
            user: components["schemas"]["User"];
        };
        MediaType: {
            schema?: components["schemas"]["Schema"];
        };
        Member: {
            email: string;
            /** Format: date-time */
            joinedAt: string;
            name: string;
            /** @enum {string} */
            role: "owner" | "admin" | "member";
            /** @enum {string} */
            roleSource: "manual" | "oidc";
            /** Format: uuid */
            userId: string;
        };
        Membership: {
            /** Format: uuid */
            orgId: string;
            orgName: string;
            orgSlug: string;
            /** @enum {string} */
            role: "owner" | "admin" | "member";
        };
        Operation: {
            description?: string;
            operationId: string;
            parameters?: components["schemas"]["Parameter"][];
            requestBody?: components["schemas"]["RequestBody"];
            responses: {
                [key: string]: components["schemas"]["Response"] | null;
            };
            security?: {
                [key: string]: string[];
            }[];
            summary?: string;
            tags?: string[];
        };
        Palette: {
            dark: {
                [key: string]: string;
            };
            light: {
                [key: string]: string;
            };
        };
        Parameter: {
            description?: string;
            in: string;
            name: string;
            required?: boolean;
            schema: components["schemas"]["Schema"] | null;
        };
        Provider: {
            clientId: string;
            createGroups: boolean;
            enabled: boolean;
            groupsClaim: string;
            hasSecret: boolean;
            issuer: string;
            scopes: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProviderView: {
            callbackUrl: string;
            provider: components["schemas"]["Provider"] | null;
        };
        ReadinessResponse: {
            routing: components["schemas"]["Stats"];
            status: string;
        };
        ReplicaStatus: {
            healthy: boolean;
            lastError?: string;
            name: string;
        };
        RequestBody: {
            content: {
                [key: string]: components["schemas"]["MediaType"];
            };
            description?: string;
            required?: boolean;
        };
        Response: {
            content?: {
                [key: string]: components["schemas"]["MediaType"];
            };
            description: string;
        };
        SaveOIDCProviderRequest: {
            clientId: string;
            clientSecret?: string;
            createGroups: boolean;
            enabled: boolean;
            groupsClaim?: string;
            issuer: string;
            scopes?: string;
        };
        Schema: {
            $defs?: {
                [key: string]: components["schemas"]["Schema"] | null;
            };
            $ref?: string;
            additionalProperties?: components["schemas"]["Schema"];
            description?: string;
            enum?: string[];
            format?: string;
            items?: components["schemas"]["Schema"];
            oneOf?: (components["schemas"]["Schema"] | null)[];
            properties?: {
                [key: string]: components["schemas"]["Schema"] | null;
            };
            required?: string[];
            /** @description A JSON value. */
            type?: unknown;
        };
        SecurityScheme: {
            description?: string;
            in?: string;
            name?: string;
            scheme?: string;
            type: string;
        };
        Server: {
            description?: string;
            url: string;
        };
        SetGroupRoleRequest: {
            group: string;
            /** @enum {string} */
            role: "admin" | "member";
        };
        Shape: {
            radiusControl?: number;
            radiusOverlay?: number;
        };
        Spec: {
            backdrop?: components["schemas"]["Backdrop"];
            colors: components["schemas"]["Palette"];
            css: string;
            cursors: {
                [key: string]: components["schemas"]["Cursor"];
            };
            effect?: string;
            fonts: components["schemas"]["Fonts"];
            icons: {
                [key: string]: components["schemas"]["Icon"];
            };
            shadows: {
                [key: string]: string;
            };
            shape: components["schemas"]["Shape"];
        };
        Stats: {
            lagFallbacks: number;
            noHealthyReplicaHits: number;
            readsToPrimary: number;
            readsToReplica: number;
            replicas: components["schemas"]["ReplicaStatus"][];
            staleFallbacks: number;
        };
        StatusResponse: {
            status: string;
        };
        SwitchOrgRequest: {
            slug: string;
        };
        Tag: {
            description?: string;
            name: string;
        };
        Theme: {
            active: boolean;
            assets: components["schemas"]["Asset"][];
            /** Format: date-time */
            createdAt: string;
            default: boolean;
            /** Format: uuid */
            id: string;
            inUse: number;
            name: string;
            /** Format: uuid */
            ownerId: string;
            ownerName: string;
            shared: boolean;
            spec: components["schemas"]["Spec"];
            /** Format: date-time */
            updatedAt: string;
        };
        User: {
            avatarUrl?: string;
            email: string;
            /** Format: uuid */
            id: string;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    oIDCCallback: {
        parameters: {
            query?: {
                state?: string;
                code?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found: the browser is sent on. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    oIDCStart: {
        parameters: {
            query?: {
                /** @description A path of this application to land on afterwards. */
                next?: string;
            };
            header?: never;
            path: {
                orgSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found: the browser is sent on. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    switchOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchOrgRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        organization: components["schemas"]["CurrentOrg"];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getOIDCProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"];
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    saveOIDCProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveOIDCProviderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"];
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listGroupRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        groupRoles: components["schemas"]["GroupRole"][];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    setGroupRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetGroupRoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        groupRole: components["schemas"]["GroupRole"];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    removeGroupRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupRoleID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    openAPI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listThemes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        themes: components["schemas"]["Theme"][];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Input"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        theme: components["schemas"]["Theme"];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    activeTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        source: string;
                        theme: components["schemas"]["Theme"] | null;
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    chooseTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChooseThemeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        theme: components["schemas"]["Theme"] | null;
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    setDefaultTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefaultThemeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        theme: components["schemas"]["Theme"] | null;
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    themeExamples: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        examples: components["schemas"]["Example"][];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    importTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        theme: components["schemas"]["Theme"];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getTheme: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                themeID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        theme: components["schemas"]["Theme"];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    deleteTheme: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                themeID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    updateTheme: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                themeID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Input"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        theme: components["schemas"]["Theme"];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    uploadThemeAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                themeID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        asset: components["schemas"]["Asset"];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    themeAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                themeID: string;
                assetID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    deleteThemeAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                themeID: string;
                assetID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    exportTheme: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                themeID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        members: components["schemas"]["Member"][];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listJoinRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        requests: components["schemas"]["JoinRequest"][];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    declineJoinRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    admitJoinRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdmitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        membership: components["schemas"]["Membership"];
                    };
                };
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, in the one shape every endpoint uses. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
