-- +goose Up
-- Editing together (#65). A page's shared draft is a Yjs document the api
-- never reads: an append log of the updates its editors send, in the order
-- the database took them. A room is one life of that document; when it is
-- thrown away or started afresh it gets a new id, so a browser holding the
-- old one never merges it into the new.
CREATE TABLE page_collab (
    org_id            uuid NOT NULL,
    page_id           uuid NOT NULL,
    id                uuid NOT NULL DEFAULT uuidv7(),
    -- The version the shared draft was begun from, moved on by each publish
    -- made from it, so a publish over somebody else's is still refused.
    base_version      integer NOT NULL,
    -- Whether its first content has arrived, and until when the one person
    -- asked to send it has to do so before somebody else is asked.
    seeded            boolean NOT NULL DEFAULT false,
    seed_until        timestamptz,
    -- The last update a publish from the room had seen; a room with nothing
    -- past it holds no unpublished change.
    published_through bigint NOT NULL DEFAULT 0,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (org_id, page_id),
    UNIQUE (org_id, page_id, id),
    FOREIGN KEY (org_id, page_id) REFERENCES page (org_id, id) ON DELETE CASCADE,
    CONSTRAINT page_collab_base_not_negative CHECK (base_version >= 0)
);

CREATE TABLE page_collab_update (
    org_id     uuid NOT NULL,
    page_id    uuid NOT NULL,
    room_id    uuid NOT NULL,
    -- By default from the identity; a compaction writes the merged update
    -- under the last number it replaces, so the order holds.
    seq        bigint GENERATED BY DEFAULT AS IDENTITY,
    body       bytea NOT NULL,
    -- Stamped by page_collab_update_stamp, never written by the app.
    created_by uuid REFERENCES app_user(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (org_id, room_id, seq),
    -- An update of a room thrown away goes with it, and one sent to it
    -- afterwards is refused, which tells its sender to start again.
    FOREIGN KEY (org_id, page_id, room_id) REFERENCES page_collab (org_id, page_id, id) ON DELETE CASCADE,
    -- collab.MaxMessageBytes, which a test holds to this.
    CONSTRAINT page_collab_update_size CHECK (octet_length(body) BETWEEN 1 AND 4194304)
);

CREATE TRIGGER page_collab_set_updated_at BEFORE UPDATE ON page_collab
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER page_collab_not_folder BEFORE INSERT ON page_collab
    FOR EACH ROW EXECUTE FUNCTION page_not_folder();

-- +goose StatementBegin
-- Who sent an update is the database's to say, so nobody writes into the
-- shared draft in somebody else's name.
CREATE FUNCTION page_collab_update_stamp() RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    NEW.created_by := current_actor_id();
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER page_collab_update_stamp BEFORE INSERT ON page_collab_update
    FOR EACH ROW EXECUTE FUNCTION page_collab_update_stamp();

ALTER TABLE page_collab        ENABLE ROW LEVEL SECURITY;
ALTER TABLE page_collab        FORCE  ROW LEVEL SECURITY;
ALTER TABLE page_collab_update ENABLE ROW LEVEL SECURITY;
ALTER TABLE page_collab_update FORCE  ROW LEVEL SECURITY;

CREATE POLICY page_collab_tenant_isolation ON page_collab
    USING (org_id = current_org_id()) WITH CHECK (org_id = current_org_id());
CREATE POLICY page_collab_admin_bypass ON page_collab TO stator_admin USING (true) WITH CHECK (true);
CREATE POLICY page_collab_update_tenant_isolation ON page_collab_update
    USING (org_id = current_org_id()) WITH CHECK (org_id = current_org_id());
CREATE POLICY page_collab_update_admin_bypass ON page_collab_update TO stator_admin USING (true) WITH CHECK (true);

-- The shared draft is the editors': only somebody who may edit the page now
-- reads it, adds to it, or throws it away, as with the edit rule anywhere,
-- so an archived page's shared draft is frozen with it.
CREATE POLICY page_collab_editors ON page_collab AS RESTRICTIVE FOR ALL TO stator_app
    USING (perm_page_editable(page_id, current_actor_id()))
    WITH CHECK (perm_page_editable(page_id, current_actor_id()));
CREATE POLICY page_collab_update_editors ON page_collab_update AS RESTRICTIVE FOR ALL TO stator_app
    USING (perm_page_editable(page_id, current_actor_id()))
    WITH CHECK (perm_page_editable(page_id, current_actor_id()));

-- Updates are appended and replaced by a compaction, never rewritten; the
-- default privileges grant UPDATE, so it is taken back.
GRANT SELECT, INSERT, UPDATE, DELETE ON page_collab TO stator_app, stator_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON page_collab_update TO stator_admin;
GRANT SELECT, INSERT, DELETE ON page_collab_update TO stator_app;
REVOKE UPDATE ON page_collab_update FROM stator_app;

-- +goose Down
DROP TABLE IF EXISTS page_collab_update;
DROP TABLE IF EXISTS page_collab;
DROP FUNCTION IF EXISTS page_collab_update_stamp();
